import type { DashboardData, DemoScenario, DroneConsoleData, ReplayLibraryItem } from "../types";

export const scenarioCoordinates: Record<string, { lat: number; lon: number; activityContext: string; suspectedSpecies?: string; month?: number }> = {
  horseshoe_reef_2026: { lat: -31.9827, lon: 115.5153, activityContext: "spearfishing", suspectedSpecies: "white shark", month: 5 },
  queensland_spearfishing_reef_tiger_bull_2026: { lat: -18.0822, lon: 146.4483, activityContext: "spearfishing", suspectedSpecies: "tiger shark", month: 5 },
  florida_crowded_beach_inlet: { lat: 29.0258, lon: -80.926, activityContext: "swimming/surfing/fishing", suspectedSpecies: "blacktip shark", month: 7 },
  hawaii_october_tiger_context: { lat: 21.276, lon: -157.824, activityContext: "general water activity", suspectedSpecies: "tiger shark", month: 10 },
  red_sea_anomaly_context: { lat: 27.2579, lon: 33.8116, activityContext: "diving/tourism corridor", suspectedSpecies: "oceanic whitetip", month: 6 },
};

export const mockDemoScenarios: DemoScenario[] = [
  {
    scenario_id: "horseshoe_reef_2026",
    label: "Horseshoe Reef 2026 surveillance replay",
    region: "Western Australia",
    context: "Low general warning with high surveillance priority from spearfishing, reef habitat, and white shark regional context.",
    activity_context: "spearfishing",
    lat: -31.9827,
    lon: 115.5153,
    public_case_study: "docs/CASE_STUDY_HORSESHOE_REEF_2026.md",
  },
  {
    scenario_id: "queensland_spearfishing_reef_tiger_bull_2026",
    label: "Queensland Spearfishing 2026 replay",
    region: "Far North Queensland, Australia",
    context: "Tropical reef spearfishing context with tiger/bull shark operational suitability.",
    activity_context: "spearfishing",
    lat: -18.0822,
    lon: 146.4483,
    public_case_study: "docs/case_studies/queensland_spearfishing_2026.md",
  },
  {
    scenario_id: "florida_crowded_beach_inlet",
    label: "Florida crowded beach and inlet context",
    region: "Florida",
    context: "Crowding, inlet/runoff, surf/fishing exposure, and blacktip/bull regional context for operational review.",
    activity_context: "swimming/surfing/fishing",
    lat: 29.0258,
    lon: -80.926,
    public_case_study: null,
  },
  {
    scenario_id: "hawaii_october_tiger_context",
    label: "Hawaii October tiger shark context",
    region: "Hawaii",
    context: "October regional attention window with tiger shark context and bounded environmental interpretation.",
    activity_context: "general water activity",
    lat: 21.276,
    lon: -157.824,
    public_case_study: null,
  },
  {
    scenario_id: "red_sea_anomaly_context",
    label: "Red Sea anomaly context",
    region: "Red Sea",
    context: "Carcass/shipping/tourism anomaly context for advisory and surveillance review.",
    activity_context: "diving/tourism corridor",
    lat: 27.2579,
    lon: 33.8116,
    public_case_study: null,
  },
];

export const mockReplayLibrary: ReplayLibraryItem[] = [
  {
    id: "horseshoe_reef_2026",
    title: "Horseshoe Reef 2026",
    region: "Western Australia",
    coordinates: { lat: -31.9827, lon: 115.5153 },
    observed_at: "2026-05-16T00:00:00Z",
    activity_context: "spearfishing",
    species_context: "white shark regional suitability",
    replay_output: { warning_score: 18, warning_band: "low", activity_hazard_score: 58, activity_hazard_band: "elevated", surveillance_priority_score: 82, surveillance_priority_band: "high", confidence: 0.68 },
    quiet_day_comparison: { warning_score: 8, activity_hazard_score: 4, surveillance_priority_score: 26, confidence: 0.72, summary: "Quiet-day baseline remains low; surveillance priority rises when activity, reef habitat, and regional context are present." },
    factor_summary: [{ factor: "activity_hazard_score", points: 20.3 }, { factor: "wa_white_shark_reef_spearfishing_context", points: 18 }, { factor: "reef_dropoff_habitat_proximity", points: 13 }],
    explanation_summary: "Low general warning with high operational surveillance priority for reef-edge review.",
    heatmap_asset: "docs/assets/horseshoe_reef_2026_model_replay.svg",
    model_version: "0.11.0",
    scoring_revision: "phase-11-explainability",
    provider_stack_version: "phase-9-static-live-adapters",
    generated_at: "2026-05-29T00:00:00Z",
    disclaimer: "AI1SAD estimates environmental and surveillance-relevant shark encounter conditions. It does not predict individual attacks or guarantee safety outcomes.",
  },
  {
    id: "queensland_spearfishing_reef_tiger_bull_2026",
    title: "Queensland Spearfishing 2026",
    region: "Far North Queensland, Australia",
    coordinates: { lat: -18.0822, lon: 146.4483 },
    observed_at: "2026-05-24T08:00:00Z",
    activity_context: "spearfishing",
    species_context: "tiger shark and bull shark operational context",
    replay_output: { warning_score: 22, warning_band: "low", activity_hazard_score: 64, activity_hazard_band: "elevated", surveillance_priority_score: 78, surveillance_priority_band: "high", confidence: 0.66 },
    quiet_day_comparison: { warning_score: 10, activity_hazard_score: 8, surveillance_priority_score: 31, confidence: 0.7, summary: "Quiet-day comparison stays lower without spearfishing, reef/dropoff, and tropical species context." },
    factor_summary: [{ factor: "activity_hazard_score", points: 22 }, { factor: "reef_dropoff_habitat_proximity", points: 13 }, { factor: "regional_species_suitability", points: 12 }],
    explanation_summary: "Tropical reef spearfishing context increases operator review priority while public warning language remains bounded.",
    heatmap_asset: "docs/assets/case_studies/queensland_spearfishing_2026_heatmap.svg",
    model_version: "0.11.0",
    scoring_revision: "phase-11-explainability",
    provider_stack_version: "phase-9-static-live-adapters",
    generated_at: "2026-05-29T00:00:00Z",
    disclaimer: "AI1SAD estimates environmental and surveillance-relevant shark encounter conditions. It does not predict individual attacks or guarantee safety outcomes.",
  },
  {
    id: "florida_crowded_inlet_demo",
    title: "Florida Crowded Inlet Demo",
    region: "Florida",
    coordinates: { lat: 29.0258, lon: -80.926 },
    observed_at: null,
    activity_context: "swimming/surfing/fishing",
    species_context: "blacktip and bull shark regional context",
    replay_output: { warning_score: 46, warning_band: "moderate", activity_hazard_score: 48, activity_hazard_band: "moderate", surveillance_priority_score: 55, surveillance_priority_band: "moderate", confidence: 0.62 },
    quiet_day_comparison: { warning_score: 18, activity_hazard_score: 14, surveillance_priority_score: 24, confidence: 0.68, summary: "Crowding, inlet exposure, and mixed water activity raise review context above a quiet-day baseline." },
    factor_summary: [{ factor: "human_exposure_index", points: 14 }, { factor: "inlet_runoff_context", points: 12 }, { factor: "activity_context", points: 10 }],
    explanation_summary: "Demo scenario for crowded inlet operations and environmental monitoring.",
    heatmap_asset: null,
    model_version: "0.11.0",
    scoring_revision: "phase-11-explainability",
    provider_stack_version: "phase-9-static-live-adapters",
    generated_at: "2026-05-29T00:00:00Z",
    disclaimer: "AI1SAD estimates environmental and surveillance-relevant shark encounter conditions. It does not predict individual attacks or guarantee safety outcomes.",
  },
  {
    id: "hawaii_october_tiger_context_demo",
    title: "Hawaii October Tiger Shark Context Demo",
    region: "Hawaii",
    coordinates: { lat: 21.276, lon: -157.824 },
    observed_at: null,
    activity_context: "general water activity",
    species_context: "tiger shark seasonal context",
    replay_output: { warning_score: 28, warning_band: "low", activity_hazard_score: 24, activity_hazard_band: "low", surveillance_priority_score: 38, surveillance_priority_band: "moderate", confidence: 0.6 },
    quiet_day_comparison: { warning_score: 16, activity_hazard_score: 12, surveillance_priority_score: 22, confidence: 0.66, summary: "Seasonal context raises operator awareness modestly without changing the bounded public warning posture." },
    factor_summary: [{ factor: "seasonal_species_context", points: 10 }, { factor: "regional_profile", points: 8 }, { factor: "human_exposure_index", points: 6 }],
    explanation_summary: "Demo scenario for October regional context and calm monitoring workflows.",
    heatmap_asset: null,
    model_version: "0.11.0",
    scoring_revision: "phase-11-explainability",
    provider_stack_version: "phase-9-static-live-adapters",
    generated_at: "2026-05-29T00:00:00Z",
    disclaimer: "AI1SAD estimates environmental and surveillance-relevant shark encounter conditions. It does not predict individual attacks or guarantee safety outcomes.",
  },
  {
    id: "red_sea_anomaly_demo",
    title: "Red Sea Anomaly Demo",
    region: "Red Sea",
    coordinates: { lat: 27.2579, lon: 33.8116 },
    observed_at: null,
    activity_context: "diving/tourism corridor",
    species_context: "oceanic whitetip anomaly context",
    replay_output: { warning_score: 52, warning_band: "moderate", activity_hazard_score: 36, activity_hazard_band: "moderate", surveillance_priority_score: 66, surveillance_priority_band: "elevated", confidence: 0.58 },
    quiet_day_comparison: { warning_score: 14, activity_hazard_score: 9, surveillance_priority_score: 20, confidence: 0.64, summary: "Anomaly context and tourism corridor exposure create a stronger operator-review case than a quiet baseline." },
    factor_summary: [{ factor: "biological_event_context", points: 18 }, { factor: "vessel_tourism_corridor", points: 12 }, { factor: "regional_species_suitability", points: 10 }],
    explanation_summary: "Demo scenario for anomaly review, advisory context, and surveillance planning.",
    heatmap_asset: null,
    model_version: "0.11.0",
    scoring_revision: "phase-11-explainability",
    provider_stack_version: "phase-9-static-live-adapters",
    generated_at: "2026-05-29T00:00:00Z",
    disclaimer: "AI1SAD estimates environmental and surveillance-relevant shark encounter conditions. It does not predict individual attacks or guarantee safety outcomes.",
  },
];

export const mockDashboardData: DashboardData = {
  warning: {
    location: { geo: { type: "Point", coordinates: [115.515, -31.983] } },
    warning_score: 18,
    warning_band: "low",
    activity_context_score: 58,
    activity_context_band: "elevated",
    surveillance_priority_score: 82,
    confidence: 0.68,
    dominant_factors: [
      { factor: "vessel_fishing_surveillance_context", points: 17.2, rationale: "Static spearfishing context supports operational review." },
      { factor: "regional_species_suitability", points: 18, rationale: "Western Australia white shark reef context." },
      { factor: "biological_event_surveillance_context", points: 6, rationale: "Reef/prey context is active but bounded." },
    ],
    data_sources_used: ["vessel_fishing_static", "biological_events_static", "regional_risk_profiles"],
    missing_data_sources: ["open_meteo", "noaa_coastwatch"],
    active_pack: "core",
    pack_features_used: ["warning_score", "surveillance_priority", "activity_hazard"],
    pack_notice: "Western Australia regional pack available for higher-resolution local rules.",
    disclaimer:
      "AI1SAD estimates environmental and surveillance-relevant shark encounter conditions. It does not predict individual attacks or guarantee safety outcomes.",
  },
  surveillance: {
    active_pack: "western_australia",
    pack_features_used: ["white_shark_reef_spearfishing", "post_incident_surveillance"],
    pack_notice: undefined,
    disclaimer:
      "AI1SAD estimates environmental and surveillance-relevant shark encounter conditions. It does not predict individual attacks or guarantee safety outcomes.",
    zones: [
      {
        zone_id: "drone:-31.983:115.515:72:spearfishing",
        surveillance_priority_score: 82,
        surveillance_priority_band: "high",
        warning_score: 18,
        activity_context_score: 58,
        center: { geo: { type: "Point", coordinates: [115.515, -31.983] } },
        radius_km: 2.5,
        recommended_pattern: "reef-edge expanding grid",
        confidence: 0.68,
        dominant_factors: [
          { factor: "wa_white_shark_reef_spearfishing_context", points: 18 },
          { factor: "activity_hazard_score", points: 20.3 },
          { factor: "vessel_fishing_surveillance_context", points: 17.2 },
        ],
      },
      {
        zone_id: "drone:-31.971:115.503:72:general",
        surveillance_priority_score: 44,
        surveillance_priority_band: "moderate",
        warning_score: 14,
        activity_context_score: 8,
        center: { geo: { type: "Point", coordinates: [115.503, -31.971] } },
        radius_km: 4,
        recommended_pattern: "coastal expanding square",
        confidence: 0.55,
        dominant_factors: [{ factor: "regional_sst_species_context", points: 3 }],
      },
    ],
  },
  explanation: {
    output_type: "location",
    location: { geo: { type: "Point", coordinates: [115.515, -31.983] } },
    active_pack: "western_australia",
    pack_features_used: ["white_shark_reef_spearfishing", "reef_surveillance"],
    pack_notice: undefined,
    warning_score: 18,
    activity_hazard_score: 58,
    surveillance_priority_score: 82,
    dominant_factors: [
      { factor: "activity_hazard_score", points: 20.3, rationale: "Activity hazard feeds surveillance priority." },
      { factor: "wa_white_shark_reef_spearfishing_context", points: 18, rationale: "Regional reef/spearfishing rule is active." },
      { factor: "reef_dropoff_habitat_proximity", points: 13, rationale: "Reef/dropoff context shapes drone search zones." },
    ],
    factor_contributions: [
      { factor: "activity_hazard_score", points: 20.3, contribution: 0.25, rationale: "Activity hazard feeds surveillance priority." },
      { factor: "wa_white_shark_reef_spearfishing_context", points: 18, contribution: 0.22, rationale: "Regional rule is active." },
      { factor: "reef_dropoff_habitat_proximity", points: 13, contribution: 0.16, rationale: "Reef/dropoff context." },
    ],
    confidence_breakdown: {
      overall_confidence: 0.68,
      confidence_band: "moderate",
      components: { coverage_confidence: 0.66, freshness_confidence: 0.72, completeness_confidence: 0.64 },
    },
    data_freshness: {
      weather_observations: { status: "missing" },
      ocean_observations: { status: "present" },
      vessel_activity: { status: "present" },
      reef_features: { status: "present" },
    },
    missing_data_sources: ["weather_observations", "recent_interactions", "sighting_reports"],
    regional_rules_triggered: ["activity_hazard_score", "wa_white_shark_reef_spearfishing_context", "reef_dropoff_habitat_proximity"],
    suppression_reasons: ["General environmental warning remains low because live-condition signals are not strongly stacked."],
    operational_interpretation:
      "AI1SAD reads this as low general environmental warning but high operational surveillance priority. That split is driven by activity, habitat, regional species suitability, or recent operational context.",
    recommended_action: "Prioritize reef edge, dropoff, and adjacent current lines with expanding drone passes.",
    recommended_surveillance_pattern: "reef_edge_expanding_grid",
    recommended_surveillance_pattern_label: "Reef-edge expanding grid",
    metadata: {
      model_version: "0.11.0",
      scoring_revision: "phase-11-explainability",
      provider_stack_version: "phase-9-static-live-adapters",
      generated_at: "2026-05-24T08:10:00Z",
    },
    disclaimer:
      "AI1SAD estimates environmental and surveillance-relevant shark encounter conditions. It does not predict individual attacks or guarantee safety outcomes.",
  },
  alerts: [
    {
      alert_type: "surveillance_priority",
      level: "watch",
      title: "Vessel or fishing context supports surveillance review",
      summary: "Spearfishing and reef context are active alongside regional species suitability.",
      recommended_action: "Prioritize targeted drone review; do not treat this as attack prediction.",
      confidence: 0.65,
      expires_at: new Date(Date.now() + 4 * 60 * 60 * 1000).toISOString(),
      zone: { location: { geo: { coordinates: [115.515, -31.983] } }, radius_km: 2.5 },
      dominant_factors: [{ factor: "vessel_fishing_context", points: 17.2 }],
    },
  ],
  providerHealth: [
    { provider: "open_meteo", status: "healthy", records_ingested: 3, last_success: "2026-05-24T08:10:00Z" },
    { provider: "noaa_nws", status: "not_applicable", records_ingested: 0, last_success: null },
    { provider: "noaa_coastwatch", status: "offline_adapter", records_ingested: 0, last_success: null },
    { provider: "human_exposure_static", status: "healthy", records_ingested: 6, last_success: "2026-05-24T08:10:00Z" },
    { provider: "biological_events_static", status: "healthy", records_ingested: 5, last_success: "2026-05-24T08:10:00Z" },
    { provider: "vessel_fishing_static", status: "healthy", records_ingested: 5, last_success: "2026-05-24T08:10:00Z" },
  ],
  packs: [
    {
      pack_id: "core",
      name: "Core",
      covered_regions: ["global"],
      dominant_species: [],
      features: ["baseline warning", "surveillance priority", "alerts"],
      required_access_tier: "free",
    },
    {
      pack_id: "western_australia",
      name: "Western Australia",
      covered_regions: ["Rottnest Island", "Perth coast", "WA reefs"],
      dominant_species: ["white shark"],
      features: ["reef/dropoff context", "spearfishing context", "white shark suitability"],
      required_access_tier: "research",
    },
    {
      pack_id: "florida",
      name: "Florida",
      covered_regions: ["Atlantic beaches", "Gulf beaches", "inlets"],
      dominant_species: ["bull shark", "blacktip shark", "spinner shark"],
      features: ["runoff", "inlet fishing", "tourism exposure"],
      required_access_tier: "developer",
    },
  ],
  replay: {
    scenario_id: "wa_spearfishing_reef_white",
    label: "Western Australia spearfishing reef replay",
    region: "western_australia",
    active_pack: "western_australia",
    pack_features_used: ["white_shark_reef_spearfishing", "replay_heatmap"],
    incident_day: {
      warning_score: 18,
      surveillance_priority_score: 82,
      activity_hazard_score: 58,
      confidence: 0.68,
    },
    quiet_day: {
      warning_score: 8,
      surveillance_priority_score: 26,
      activity_hazard_score: 4,
      confidence: 0.72,
    },
    confidence_decomposition: {
      weather: 0.12,
      sst: 0.14,
      vessel_activity: 0.16,
      biological_events: 0.12,
      human_exposure: 0.1,
    },
    signal_decay_timeline: [
      { signal_type: "spearfishing_activity", age_hours: 2, decay_weight: 0.84, decayed_value: 0.74 },
      { signal_type: "biological_event", age_hours: 18, decay_weight: 0.84, decayed_value: 0.42 },
      { signal_type: "pier_fishing_pressure", age_hours: 36, decay_weight: 0.71, decayed_value: 0.51 },
    ],
  },
  replayLibrary: mockReplayLibrary,
  replayHeatmap: {
    score_type: "surveillance_priority_score",
    config: { center_lat: -31.983, center_lon: 115.515, radius_km: 8, grid_cells: 9 },
    cells: [
      { lat: -31.995, lon: 115.493, surveillance_priority_score: 35, surveillance_priority_band: "moderate", warning_score: 14, warning_band: "low", activity_hazard_score: 24, activity_hazard_band: "moderate" },
      { lat: -31.995, lon: 115.515, surveillance_priority_score: 49, surveillance_priority_band: "moderate", warning_score: 16, warning_band: "low", activity_hazard_score: 34, activity_hazard_band: "moderate" },
      { lat: -31.995, lon: 115.537, surveillance_priority_score: 42, surveillance_priority_band: "moderate", warning_score: 12, warning_band: "low", activity_hazard_score: 26, activity_hazard_band: "moderate" },
      { lat: -31.983, lon: 115.493, surveillance_priority_score: 58, surveillance_priority_band: "elevated", warning_score: 17, warning_band: "low", activity_hazard_score: 48, activity_hazard_band: "elevated" },
      { lat: -31.983, lon: 115.515, surveillance_priority_score: 82, surveillance_priority_band: "high", warning_score: 18, warning_band: "low", activity_hazard_score: 58, activity_hazard_band: "elevated" },
      { lat: -31.983, lon: 115.537, surveillance_priority_score: 61, surveillance_priority_band: "elevated", warning_score: 15, warning_band: "low", activity_hazard_score: 44, activity_hazard_band: "elevated" },
      { lat: -31.971, lon: 115.493, surveillance_priority_score: 28, surveillance_priority_band: "low", warning_score: 10, warning_band: "low", activity_hazard_score: 12, activity_hazard_band: "low" },
      { lat: -31.971, lon: 115.515, surveillance_priority_score: 44, surveillance_priority_band: "moderate", warning_score: 14, warning_band: "low", activity_hazard_score: 22, activity_hazard_band: "moderate" },
      { lat: -31.971, lon: 115.537, surveillance_priority_score: 30, surveillance_priority_band: "low", warning_score: 9, warning_band: "low", activity_hazard_score: 10, activity_hazard_band: "low" },
    ],
    statistics: { min_score: 28, max_score: 82, avg_score: 47.67, median_score: 44 },
  },
  demoScenarios: mockDemoScenarios,
  demoStatus: {
    demo_mode: true,
    mode: "demo",
    database_configured: false,
    admin_writes_enabled: false,
    private_internal_data_exposed: false,
    disclaimer:
      "AI1SAD estimates environmental and surveillance-relevant shark encounter conditions. It does not predict individual attacks or guarantee safety outcomes.",
  },
};

export const mockDroneConsoleData: DroneConsoleData = {
  data_source: "mock",
  missions: [
    {
      mission: {
        mission_id: "mission-panama-city-mavlink-demo",
        drone_id: "drone-panama-city-mavlink-demo",
        operator_role: "human_drone_operator",
        region: "Panama City Beach, Florida",
        pack_id: "florida",
        mission_type: "shoreline_parallel_sweep",
        started_at: "2026-06-08T17:00:00Z",
        status: "active",
        recommended_pattern: "shoreline_parallel_sweep",
        human_approved: true,
        autonomous_flight_control: false,
        source: "demo_fixture",
        visibility: "public",
        notes_public: "Safe local demo mission for human-entered drone observations.",
      },
      latestTelemetry: {
        timestamp: "2026-06-08T17:04:00Z",
        latitude: 30.1829,
        longitude: -85.7544,
        altitude_m: 38,
        heading_deg: 102,
        groundspeed_mps: 4.2,
        battery_percent: 84,
        gps_fix_quality: "3d",
        source: "mavlink_bridge",
        source_type: "fixture_replay",
      },
    },
    {
      mission: {
        mission_id: "mission-surf-line-observer-demo",
        drone_id: "coastal-observer",
        operator_role: "lifeguard_visual",
        region: "Local surf-line observation demo",
        pack_id: "core",
        mission_type: "manual_observation_patrol",
        started_at: "2026-06-08T18:00:00Z",
        status: "active",
        recommended_pattern: "lifeguard_observation_coordination",
        human_approved: true,
        autonomous_flight_control: false,
        source: "demo_fixture",
        visibility: "public",
        notes_public: "Demo mission for non-aircraft coastal observers.",
      },
      latestTelemetry: null,
    },
  ],
  observations: [
    {
      observation_id: "observation-demo-no-sighting-1",
      mission_id: "mission-panama-city-mavlink-demo",
      drone_id: "drone-panama-city-mavlink-demo",
      timestamp: "2026-06-08T17:05:00Z",
      latitude: 30.1828,
      longitude: -85.7541,
      observation_type: "no_sighting_patrol_result",
      count: 0,
      confidence: 0.62,
      review_status: "operator_reviewed",
      source: "demo_fixture",
      source_type: "drone_operator_visual",
      visibility: "public",
      public_visibility: true,
      active_pack: "florida",
      recommended_surveillance_pattern: "shoreline_parallel_sweep",
    },
    {
      observation_id: "observation-demo-surf-line-1",
      mission_id: "mission-surf-line-observer-demo",
      drone_id: "coastal-observer",
      timestamp: "2026-06-08T18:07:00Z",
      latitude: 30.1834,
      longitude: -85.755,
      observation_type: "surf_line_activity",
      count: 12,
      confidence: 0.58,
      review_status: "operator_reviewed",
      source: "demo_fixture",
      source_type: "lifeguard_visual",
      visibility: "public",
      public_visibility: true,
      active_pack: "core",
      recommended_surveillance_pattern: "lifeguard_observation_coordination",
    },
  ],
  feed: {
    disclaimer:
      "AI1SAD estimates environmental and surveillance-relevant shark encounter conditions. It does not predict individual attacks or guarantee safety outcomes.",
    results: [
      {
        latitude: 30.1828,
        longitude: -85.7541,
        timestamp: "2026-06-08T17:05:00Z",
        observation_type: "no_sighting_patrol_result",
        review_status: "operator_reviewed",
        confidence: 0.62,
        mission_id: "mission-panama-city-mavlink-demo",
        source_type: "drone_operator_visual",
        active_pack: "florida",
        explanation_summary: "No-sighting patrol result reduces uncertainty only inside documented coverage and time window.",
        recommended_action: "Do not treat no-sighting patrol as proof of safety; continue official guidance.",
        recommended_surveillance_pattern: "shoreline_parallel_sweep",
        expires_at: "2026-06-08T20:05:00Z",
        data_freshness: { status: "fresh", source: "drone_observation_intake" },
      },
      {
        latitude: 30.1834,
        longitude: -85.755,
        timestamp: "2026-06-08T18:07:00Z",
        observation_type: "surf_line_activity",
        review_status: "operator_reviewed",
        confidence: 0.58,
        mission_id: "mission-surf-line-observer-demo",
        source_type: "lifeguard_visual",
        active_pack: "core",
        explanation_summary: "Drone surf_line_activity report is source-attributed and review status is operator_reviewed.",
        recommended_action: "Review observation, source confidence, and local official guidance before operational escalation.",
        recommended_surveillance_pattern: "lifeguard_observation_coordination",
        expires_at: "2026-06-08T21:07:00Z",
        data_freshness: { status: "fresh", source: "drone_observation_intake" },
      },
    ],
    surveillance: {
      zones: [
        {
          zone_id: "drone-observation-review:panama-city-demo",
          surveillance_priority_score: 24,
          surveillance_priority_band: "low",
          warning_score: 0,
          activity_context_score: 8,
          center: { geo: { type: "Point", coordinates: [-85.7541, 30.1828] } },
          radius_km: 2,
          recommended_pattern: "shoreline_parallel_sweep",
          dominant_factors: [{ factor: "no_sighting_patrol_result", points: 0 }],
          confidence: 0.56,
        },
      ],
      disclaimer:
        "AI1SAD estimates environmental and surveillance-relevant shark encounter conditions. It does not predict individual attacks or guarantee safety outcomes.",
    },
    alerts: [],
    flight_control: {
      autonomous_flight_control: false,
      commands_exposed: false,
      human_approval_required: true,
    },
  },
};
