import type { DashboardData, DemoScenario } from "../types";

export const scenarioCoordinates: Record<string, { lat: number; lon: number; activityContext: string; suspectedSpecies?: string; month?: number }> = {
  horseshoe_reef_2026: { lat: -31.9827, lon: 115.5153, activityContext: "spearfishing", suspectedSpecies: "white shark", month: 5 },
  queensland_spearfishing_reef_tiger_bull_2026: { lat: -18.0822, lon: 146.4483, activityContext: "spearfishing", suspectedSpecies: "tiger shark", month: 5 },
  florida_crowded_beach_inlet: { lat: 29.0258, lon: -80.926, activityContext: "swimming/surfing/fishing", suspectedSpecies: "blacktip shark", month: 7 },
  hawaii_october_tiger_context: { lat: 21.276, lon: -157.824, activityContext: "general water activity", suspectedSpecies: "tiger shark", month: 10 },
  red_sea_anomaly_context: { lat: 27.2579, lon: 33.8116, activityContext: "diving/tourism corridor", suspectedSpecies: "oceanic whitetip", month: 6 },
};

export const mockDemoScenarios: DemoScenario[] = [
  {
    scenario_id: "horseshoe_reef_2026",
    label: "Horseshoe Reef 2026 surveillance replay",
    region: "Western Australia",
    context: "Low general warning with high surveillance priority from spearfishing, reef habitat, and white shark regional context.",
    activity_context: "spearfishing",
    lat: -31.9827,
    lon: 115.5153,
    public_case_study: "docs/CASE_STUDY_HORSESHOE_REEF_2026.md",
  },
  {
    scenario_id: "queensland_spearfishing_reef_tiger_bull_2026",
    label: "Queensland Spearfishing 2026 replay",
    region: "Far North Queensland, Australia",
    context: "Tropical reef spearfishing context with tiger/bull shark operational suitability.",
    activity_context: "spearfishing",
    lat: -18.0822,
    lon: 146.4483,
    public_case_study: "docs/case_studies/queensland_spearfishing_2026.md",
  },
  {
    scenario_id: "florida_crowded_beach_inlet",
    label: "Florida crowded beach and inlet context",
    region: "Florida",
    context: "Crowding, inlet/runoff, surf/fishing exposure, and blacktip/bull regional context for operational review.",
    activity_context: "swimming/surfing/fishing",
    lat: 29.0258,
    lon: -80.926,
    public_case_study: null,
  },
  {
    scenario_id: "hawaii_october_tiger_context",
    label: "Hawaii October tiger shark context",
    region: "Hawaii",
    context: "October regional attention window with tiger shark context and bounded environmental interpretation.",
    activity_context: "general water activity",
    lat: 21.276,
    lon: -157.824,
    public_case_study: null,
  },
  {
    scenario_id: "red_sea_anomaly_context",
    label: "Red Sea anomaly context",
    region: "Red Sea",
    context: "Carcass/shipping/tourism anomaly context for advisory and surveillance review.",
    activity_context: "diving/tourism corridor",
    lat: 27.2579,
    lon: 33.8116,
    public_case_study: null,
  },
];

export const mockDashboardData: DashboardData = {
  warning: {
    location: { geo: { type: "Point", coordinates: [115.515, -31.983] } },
    warning_score: 18,
    warning_band: "low",
    activity_context_score: 58,
    activity_context_band: "elevated",
    surveillance_priority_score: 82,
    confidence: 0.68,
    dominant_factors: [
      { factor: "vessel_fishing_surveillance_context", points: 17.2, rationale: "Static spearfishing context supports operational review." },
      { factor: "regional_species_suitability", points: 18, rationale: "Western Australia white shark reef context." },
      { factor: "biological_event_surveillance_context", points: 6, rationale: "Reef/prey context is active but bounded." },
    ],
    data_sources_used: ["vessel_fishing_static", "biological_events_static", "regional_risk_profiles"],
    missing_data_sources: ["open_meteo", "noaa_coastwatch"],
    active_pack: "core",
    pack_features_used: ["warning_score", "surveillance_priority", "activity_hazard"],
    pack_notice: "Western Australia regional pack available for higher-resolution local rules.",
    disclaimer:
      "AI1SAD estimates environmental and surveillance-relevant shark encounter conditions. It does not predict individual attacks or guarantee safety outcomes.",
  },
  surveillance: {
    active_pack: "western_australia",
    pack_features_used: ["white_shark_reef_spearfishing", "post_incident_surveillance"],
    pack_notice: undefined,
    disclaimer:
      "AI1SAD estimates environmental and surveillance-relevant shark encounter conditions. It does not predict individual attacks or guarantee safety outcomes.",
    zones: [
      {
        zone_id: "drone:-31.983:115.515:72:spearfishing",
        surveillance_priority_score: 82,
        surveillance_priority_band: "high",
        warning_score: 18,
        activity_context_score: 58,
        center: { geo: { type: "Point", coordinates: [115.515, -31.983] } },
        radius_km: 2.5,
        recommended_pattern: "reef-edge expanding grid",
        confidence: 0.68,
        dominant_factors: [
          { factor: "wa_white_shark_reef_spearfishing_context", points: 18 },
          { factor: "activity_hazard_score", points: 20.3 },
          { factor: "vessel_fishing_surveillance_context", points: 17.2 },
        ],
      },
      {
        zone_id: "drone:-31.971:115.503:72:general",
        surveillance_priority_score: 44,
        surveillance_priority_band: "moderate",
        warning_score: 14,
        activity_context_score: 8,
        center: { geo: { type: "Point", coordinates: [115.503, -31.971] } },
        radius_km: 4,
        recommended_pattern: "coastal expanding square",
        confidence: 0.55,
        dominant_factors: [{ factor: "regional_sst_species_context", points: 3 }],
      },
    ],
  },
  explanation: {
    output_type: "location",
    location: { geo: { type: "Point", coordinates: [115.515, -31.983] } },
    active_pack: "western_australia",
    pack_features_used: ["white_shark_reef_spearfishing", "reef_surveillance"],
    pack_notice: undefined,
    warning_score: 18,
    activity_hazard_score: 58,
    surveillance_priority_score: 82,
    dominant_factors: [
      { factor: "activity_hazard_score", points: 20.3, rationale: "Activity hazard feeds surveillance priority." },
      { factor: "wa_white_shark_reef_spearfishing_context", points: 18, rationale: "Regional reef/spearfishing rule is active." },
      { factor: "reef_dropoff_habitat_proximity", points: 13, rationale: "Reef/dropoff context shapes drone search zones." },
    ],
    factor_contributions: [
      { factor: "activity_hazard_score", points: 20.3, contribution: 0.25, rationale: "Activity hazard feeds surveillance priority." },
      { factor: "wa_white_shark_reef_spearfishing_context", points: 18, contribution: 0.22, rationale: "Regional rule is active." },
      { factor: "reef_dropoff_habitat_proximity", points: 13, contribution: 0.16, rationale: "Reef/dropoff context." },
    ],
    confidence_breakdown: {
      overall_confidence: 0.68,
      confidence_band: "moderate",
      components: { coverage_confidence: 0.66, freshness_confidence: 0.72, completeness_confidence: 0.64 },
    },
    data_freshness: {
      weather_observations: { status: "missing" },
      ocean_observations: { status: "present" },
      vessel_activity: { status: "present" },
      reef_features: { status: "present" },
    },
    missing_data_sources: ["weather_observations", "recent_interactions", "sighting_reports"],
    regional_rules_triggered: ["activity_hazard_score", "wa_white_shark_reef_spearfishing_context", "reef_dropoff_habitat_proximity"],
    suppression_reasons: ["General environmental warning remains low because live-condition signals are not strongly stacked."],
    operational_interpretation:
      "AI1SAD reads this as low general environmental warning but high operational surveillance priority. That split is driven by activity, habitat, regional species suitability, or recent operational context.",
    recommended_action: "Prioritize reef edge, dropoff, and adjacent current lines with expanding drone passes.",
    recommended_surveillance_pattern: "reef_edge_expanding_grid",
    recommended_surveillance_pattern_label: "Reef-edge expanding grid",
    metadata: {
      model_version: "0.11.0",
      scoring_revision: "phase-11-explainability",
      provider_stack_version: "phase-9-static-live-adapters",
      generated_at: "2026-05-24T08:10:00Z",
    },
    disclaimer:
      "AI1SAD estimates environmental and surveillance-relevant shark encounter conditions. It does not predict individual attacks or guarantee safety outcomes.",
  },
  alerts: [
    {
      alert_type: "surveillance_priority",
      level: "watch",
      title: "Vessel or fishing context supports surveillance review",
      summary: "Spearfishing and reef context are active alongside regional species suitability.",
      recommended_action: "Prioritize targeted drone review; do not treat this as attack prediction.",
      confidence: 0.65,
      expires_at: new Date(Date.now() + 4 * 60 * 60 * 1000).toISOString(),
      zone: { location: { geo: { coordinates: [115.515, -31.983] } }, radius_km: 2.5 },
      dominant_factors: [{ factor: "vessel_fishing_context", points: 17.2 }],
    },
  ],
  providerHealth: [
    { provider: "open_meteo", status: "healthy", records_ingested: 3, last_success: "2026-05-24T08:10:00Z" },
    { provider: "noaa_nws", status: "not_applicable", records_ingested: 0, last_success: null },
    { provider: "noaa_coastwatch", status: "offline_adapter", records_ingested: 0, last_success: null },
    { provider: "human_exposure_static", status: "healthy", records_ingested: 6, last_success: "2026-05-24T08:10:00Z" },
    { provider: "biological_events_static", status: "healthy", records_ingested: 5, last_success: "2026-05-24T08:10:00Z" },
    { provider: "vessel_fishing_static", status: "healthy", records_ingested: 5, last_success: "2026-05-24T08:10:00Z" },
  ],
  packs: [
    {
      pack_id: "core",
      name: "Core",
      covered_regions: ["global"],
      dominant_species: [],
      features: ["baseline warning", "surveillance priority", "alerts"],
      required_access_tier: "free",
    },
    {
      pack_id: "western_australia",
      name: "Western Australia",
      covered_regions: ["Rottnest Island", "Perth coast", "WA reefs"],
      dominant_species: ["white shark"],
      features: ["reef/dropoff context", "spearfishing context", "white shark suitability"],
      required_access_tier: "research",
    },
    {
      pack_id: "florida",
      name: "Florida",
      covered_regions: ["Atlantic beaches", "Gulf beaches", "inlets"],
      dominant_species: ["bull shark", "blacktip shark", "spinner shark"],
      features: ["runoff", "inlet fishing", "tourism exposure"],
      required_access_tier: "developer",
    },
  ],
  replay: {
    scenario_id: "wa_spearfishing_reef_white",
    label: "Western Australia spearfishing reef replay",
    region: "western_australia",
    active_pack: "western_australia",
    pack_features_used: ["white_shark_reef_spearfishing", "replay_heatmap"],
    incident_day: {
      warning_score: 18,
      surveillance_priority_score: 82,
      activity_hazard_score: 58,
      confidence: 0.68,
    },
    quiet_day: {
      warning_score: 8,
      surveillance_priority_score: 26,
      activity_hazard_score: 4,
      confidence: 0.72,
    },
    confidence_decomposition: {
      weather: 0.12,
      sst: 0.14,
      vessel_activity: 0.16,
      biological_events: 0.12,
      human_exposure: 0.1,
    },
    signal_decay_timeline: [
      { signal_type: "spearfishing_activity", age_hours: 2, decay_weight: 0.84, decayed_value: 0.74 },
      { signal_type: "biological_event", age_hours: 18, decay_weight: 0.84, decayed_value: 0.42 },
      { signal_type: "pier_fishing_pressure", age_hours: 36, decay_weight: 0.71, decayed_value: 0.51 },
    ],
  },
  replayHeatmap: {
    score_type: "surveillance_priority_score",
    config: { center_lat: -31.983, center_lon: 115.515, radius_km: 8, grid_cells: 9 },
    cells: [
      { lat: -31.995, lon: 115.493, surveillance_priority_score: 35, surveillance_priority_band: "moderate", warning_score: 14, warning_band: "low", activity_hazard_score: 24, activity_hazard_band: "moderate" },
      { lat: -31.995, lon: 115.515, surveillance_priority_score: 49, surveillance_priority_band: "moderate", warning_score: 16, warning_band: "low", activity_hazard_score: 34, activity_hazard_band: "moderate" },
      { lat: -31.995, lon: 115.537, surveillance_priority_score: 42, surveillance_priority_band: "moderate", warning_score: 12, warning_band: "low", activity_hazard_score: 26, activity_hazard_band: "moderate" },
      { lat: -31.983, lon: 115.493, surveillance_priority_score: 58, surveillance_priority_band: "elevated", warning_score: 17, warning_band: "low", activity_hazard_score: 48, activity_hazard_band: "elevated" },
      { lat: -31.983, lon: 115.515, surveillance_priority_score: 82, surveillance_priority_band: "high", warning_score: 18, warning_band: "low", activity_hazard_score: 58, activity_hazard_band: "elevated" },
      { lat: -31.983, lon: 115.537, surveillance_priority_score: 61, surveillance_priority_band: "elevated", warning_score: 15, warning_band: "low", activity_hazard_score: 44, activity_hazard_band: "elevated" },
      { lat: -31.971, lon: 115.493, surveillance_priority_score: 28, surveillance_priority_band: "low", warning_score: 10, warning_band: "low", activity_hazard_score: 12, activity_hazard_band: "low" },
      { lat: -31.971, lon: 115.515, surveillance_priority_score: 44, surveillance_priority_band: "moderate", warning_score: 14, warning_band: "low", activity_hazard_score: 22, activity_hazard_band: "moderate" },
      { lat: -31.971, lon: 115.537, surveillance_priority_score: 30, surveillance_priority_band: "low", warning_score: 9, warning_band: "low", activity_hazard_score: 10, activity_hazard_band: "low" },
    ],
    statistics: { min_score: 28, max_score: 82, avg_score: 47.67, median_score: 44 },
  },
  demoScenarios: mockDemoScenarios,
  demoStatus: {
    demo_mode: true,
    mode: "demo",
    database_configured: false,
    admin_writes_enabled: false,
    private_internal_data_exposed: false,
    disclaimer:
      "AI1SAD estimates environmental and surveillance-relevant shark encounter conditions. It does not predict individual attacks or guarantee safety outcomes.",
  },
};
