import type { DashboardData } from "../types";

export const mockDashboardData: DashboardData = {
  warning: {
    location: { geo: { type: "Point", coordinates: [115.515, -31.983] } },
    warning_score: 18,
    warning_band: "low",
    activity_context_score: 58,
    activity_context_band: "elevated",
    surveillance_priority_score: 82,
    confidence: 0.68,
    dominant_factors: [
      { factor: "vessel_fishing_surveillance_context", points: 17.2, rationale: "Static spearfishing context supports operational review." },
      { factor: "regional_species_suitability", points: 18, rationale: "Western Australia white shark reef context." },
      { factor: "biological_event_surveillance_context", points: 6, rationale: "Reef/prey context is active but bounded." },
    ],
    data_sources_used: ["vessel_fishing_static", "biological_events_static", "regional_risk_profiles"],
    missing_data_sources: ["open_meteo", "noaa_coastwatch"],
    active_pack: "core",
    pack_features_used: ["warning_score", "surveillance_priority", "activity_hazard"],
    pack_notice: "Western Australia regional pack available for higher-resolution local rules.",
    disclaimer:
      "AI1SAD estimates environmental and surveillance-relevant shark encounter conditions. It does not predict individual attacks or guarantee safety outcomes.",
  },
  surveillance: {
    active_pack: "western_australia",
    pack_features_used: ["white_shark_reef_spearfishing", "post_incident_surveillance"],
    pack_notice: undefined,
    disclaimer:
      "AI1SAD estimates environmental and surveillance-relevant shark encounter conditions. It does not predict individual attacks or guarantee safety outcomes.",
    zones: [
      {
        zone_id: "drone:-31.983:115.515:72:spearfishing",
        surveillance_priority_score: 82,
        surveillance_priority_band: "high",
        warning_score: 18,
        activity_context_score: 58,
        center: { geo: { type: "Point", coordinates: [115.515, -31.983] } },
        radius_km: 2.5,
        recommended_pattern: "reef-edge expanding grid",
        confidence: 0.68,
        dominant_factors: [
          { factor: "wa_white_shark_reef_spearfishing_context", points: 18 },
          { factor: "activity_hazard_score", points: 20.3 },
          { factor: "vessel_fishing_surveillance_context", points: 17.2 },
        ],
      },
      {
        zone_id: "drone:-31.971:115.503:72:general",
        surveillance_priority_score: 44,
        surveillance_priority_band: "moderate",
        warning_score: 14,
        activity_context_score: 8,
        center: { geo: { type: "Point", coordinates: [115.503, -31.971] } },
        radius_km: 4,
        recommended_pattern: "coastal expanding square",
        confidence: 0.55,
        dominant_factors: [{ factor: "regional_sst_species_context", points: 3 }],
      },
    ],
  },
  alerts: [
    {
      alert_type: "surveillance_priority",
      level: "watch",
      title: "Vessel or fishing context supports surveillance review",
      summary: "Spearfishing and reef context are active alongside regional species suitability.",
      recommended_action: "Prioritize targeted drone review; do not treat this as attack prediction.",
      confidence: 0.65,
      expires_at: new Date(Date.now() + 4 * 60 * 60 * 1000).toISOString(),
      zone: { location: { geo: { coordinates: [115.515, -31.983] } }, radius_km: 2.5 },
      dominant_factors: [{ factor: "vessel_fishing_context", points: 17.2 }],
    },
  ],
  providerHealth: [
    { provider: "open_meteo", status: "healthy", records_ingested: 3, last_success: "2026-05-24T08:10:00Z" },
    { provider: "noaa_nws", status: "not_applicable", records_ingested: 0, last_success: null },
    { provider: "noaa_coastwatch", status: "offline_adapter", records_ingested: 0, last_success: null },
    { provider: "human_exposure_static", status: "healthy", records_ingested: 6, last_success: "2026-05-24T08:10:00Z" },
    { provider: "biological_events_static", status: "healthy", records_ingested: 5, last_success: "2026-05-24T08:10:00Z" },
    { provider: "vessel_fishing_static", status: "healthy", records_ingested: 5, last_success: "2026-05-24T08:10:00Z" },
  ],
  packs: [
    {
      pack_id: "core",
      name: "Core",
      covered_regions: ["global"],
      dominant_species: [],
      features: ["baseline warning", "surveillance priority", "alerts"],
      required_access_tier: "free",
    },
    {
      pack_id: "western_australia",
      name: "Western Australia",
      covered_regions: ["Rottnest Island", "Perth coast", "WA reefs"],
      dominant_species: ["white shark"],
      features: ["reef/dropoff context", "spearfishing context", "white shark suitability"],
      required_access_tier: "research",
    },
    {
      pack_id: "florida",
      name: "Florida",
      covered_regions: ["Atlantic beaches", "Gulf beaches", "inlets"],
      dominant_species: ["bull shark", "blacktip shark", "spinner shark"],
      features: ["runoff", "inlet fishing", "tourism exposure"],
      required_access_tier: "developer",
    },
  ],
  replay: {
    scenario_id: "wa_spearfishing_reef_white",
    label: "Western Australia spearfishing reef replay",
    region: "western_australia",
    active_pack: "western_australia",
    pack_features_used: ["white_shark_reef_spearfishing", "replay_heatmap"],
    incident_day: {
      warning_score: 18,
      surveillance_priority_score: 82,
      activity_hazard_score: 58,
      confidence: 0.68,
    },
    quiet_day: {
      warning_score: 8,
      surveillance_priority_score: 26,
      activity_hazard_score: 4,
      confidence: 0.72,
    },
    confidence_decomposition: {
      weather: 0.12,
      sst: 0.14,
      vessel_activity: 0.16,
      biological_events: 0.12,
      human_exposure: 0.1,
    },
    signal_decay_timeline: [
      { signal_type: "spearfishing_activity", age_hours: 2, decay_weight: 0.84, decayed_value: 0.74 },
      { signal_type: "biological_event", age_hours: 18, decay_weight: 0.84, decayed_value: 0.42 },
      { signal_type: "pier_fishing_pressure", age_hours: 36, decay_weight: 0.71, decayed_value: 0.51 },
    ],
  },
};
